### ISSUE TITLE
Error when using `fromString`

### ISSUE THREAD

**Issue by jlongster** [sweet-js/sweet.js#569] opened 2016-08-12 19:07 UTC
Trying to take operators like `<` and return something like `{ op: "<" }`:

``` js
syntax foo = function(ctx) {
  const op = ctx.next().value;
  const x = #`dummy`.get(0);
  return #`{ op: ${x.fromString(op.val())} }`;
}

foo +=;
```

The above fails with `Error: [assertion error]: all tokens must have line info`.

Just doing #`{ op: null }` works as well as #`${x.fromString(op.val())} }` so it's a weird combination of the two.

**Comment by jlongster** [comment] 2016-08-14 01:26
This works:

```js
syntax foo = function(ctx) {
  let op = ctx.next().value;
  op = #`${op.fromString(op.val())}`;
  return #`{ op: ${op} }`;
}

foo +=;
```

For some reason I can't inline the `op.fromString` expression. This happens even with string literals:

```js
syntax foo = function(ctx) {
  let dummy = #`dummy`.get(0);
  return #`x ${dummy.fromString("hi")}`;
}

// Error!
foo;
```

The above code fails, but if you remove the `x` from the template it works.

**Comment by gabejohnson** [comment] 2016-08-14 02:01
There's an assumption on https://github.com/sweet-js/sweet.js/blob/aee31d07bafd6c582ec68875886e1dd4ab7d7b60/src/template-processor.js#L55 that if `to` is a `Syntax` object that it also has `slice` data.

@jlongster your working examples fail that check and the call to `setLineNumber` is never made.

I think a check for `slice` _should_ do it.

**Comment by gabejohnson** [comment] 2016-08-14 02:10
I spoke too soon. There is a `Term::setLineNumber` as well.

**Comment by jlongster** [comment] 2016-08-14 02:10
> I think a check for slice should do it.

That does fix it, but I don't know if it introduces any regressions. Should it check `to.slice` or `from.slice`? Seem like it should check `from` as you are cloning *onto* `to` so it seems like that shouldn't have location info in the first place.

**Comment by gabejohnson** [comment] 2016-08-14 02:18
It does introduce a regression. I'm trying to track down the cause as we speak.

**Comment by gabejohnson** [comment] 2016-08-14 02:36
Nope that was just me fat fingering. All of the tests still pass.

**Comment by gabejohnson** [comment] 2016-08-14 02:48
> Seem like it should check from as you are cloning onto to so it seems like that shouldn't have location info in the first place.

`to` will have location info if it was a pre-existing `Syntax` object. It's when one is created w/ `.from`* that there's a lack of info.

It should probably check both `to` and `from`, but the assertion that throws the error is pretty clear about tokens having to have location info. But that obviously doesn't make sense in this case.

@disnet?

**Comment by disnet** [comment] 2016-08-17 16:23
Actually, I think what we need to do is make the `from*` methods copy `slice` to the new syntax object. It was just an oversight that they weren't already; much better to have the invariant that *all* syntax objects flowing through the expander have line info.

**Comment by gabejohnson** [comment] 2016-08-18 13:42
@disnet should this be added in the `Syntax` constuctor?
https://github.com/sweet-js/sweet.js/blob/278e5db0e14c00dec0aac8273a21e720bc7ef6de/src/syntax.js#L172

**Comment by disnet** [comment] 2016-08-19 04:41
@gabejohnson `Syntax.from`.

Or more accurately, the various `Types.create` functions that call `new Syntax` with a brand new token. Maybe we should have a token constructor?

**Comment by gabejohnson** [comment] 2016-08-20 01:52
@disnet a token constructor is fine. It would cut down on some code. What's the signature?

Also, why wouldn't we copy over `slice` from the token of `oldstx` in the `Syntax` constructor?

**Comment by disnet** [comment] 2016-08-20 21:18
`Token(type, value, slice)` maybe?

We wouldn't want to copy `slice` by default in the `Syntax` constructor because sometimes the `slice` in the provided `token` is fine.

**Comment by disnet** [comment] 2016-08-22 00:19
I made a partial fix for this since it was holding up the build of 2.2.0. I think a real fix involves refactoring how we handle `Term`s, `Syntax`, and `Token`s, which I'm playing around with now.

**Comment by gabejohnson** [comment] 2017-01-19 17:12
@disnet Do we want to make a `Token` spec similar to the new `Term` spec?

**Comment by gabejohnson** [comment] 2017-01-19 17:16
Incidentally I think this is fixed
```javascript
syntax foo = function(ctx) {
  const op = ctx.next().value;
  const x = #`dummy`.get(0);
  return #`{ op: ${x.fromString(op.value.val())} }`;
}

foo +=;
// ;
// {
//   op: "+=";
// }
// ;
```

**Comment by disnet** [comment] 2017-01-24 19:07
> Do we want to make a `Token` spec similar to the new `Term` spec?

Hold off for now. The spec macro is in need of cleaning.

**Closed** 2017-01-24 19:08 UTC
Labels: type: bug
